# Generated by Django 5.0.6 on 2024-06-06 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centro_gestor', models.CharField(max_length=20)),
                ('centro_solicitante', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100, null=True)),
                ('mat', models.IntegerField(blank=True, null=True, verbose_name='Matrícula')),
                ('cargo', models.CharField(max_length=50)),
                ('fone', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, choices=[('I', 'OPEX'), ('II', 'CAPEX')], max_length=100, null=True)),
                ('custo_despesa', models.CharField(choices=[('I', 'Base Principal'), ('II', 'Serviços Especializados'), ('III', 'Despesas Compartilhadas'), ('IV', 'Máquinas e Equipamentos'), ('V', 'Equip. de Informática'), ('VI', 'Software e Licenças')], default='I', max_length=100)),
                ('descricao_resumida', models.CharField(blank=True, max_length=255, null=True)),
                ('classificacao_orcamento', models.CharField(blank=True, choices=[('NOVO', 'NOVO'), ('RENOVAÇÃO', 'RENOVAÇÃO'), ('CARY OVER', 'CARY OVER'), ('REPLANEJAMENTO', 'REPLANEJAMENTO')], max_length=100, null=True)),
                ('status_processo', models.CharField(blank=True, choices=[('I', 'PLANEJAMENTO'), ('II', 'Execução'), ('III', 'Elaboração de TR'), ('IV', 'Cotação'), ('V', 'Em proc. aditivo')], max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('I', 'SERVIÇO'), ('II', 'FORNECIMENTO'), ('III', 'ASSINATURA'), ('IV', 'FORNECIMENTO/SERVIÇO')], max_length=100, null=True)),
                ('valor_orcado', models.FloatField(blank=True, default=0, null=True)),
                ('valor_utilizado', models.FloatField(blank=True, default=0, null=True)),
                ('remanejamento', models.FloatField(blank=True, default=0, null=True)),
                ('mes_referencia', models.CharField(blank=True, max_length=7, null=True)),
                ('data_prevista_tr', models.DateField(blank=True, null=True)),
                ('status_elaboracao_tr', models.CharField(blank=True, choices=[('I', 'VENCIDO'), ('II', 'DENTRO DO PRAZO'), ('III', 'ELABORADO COM ATRASO'), ('IV', 'ELABORADO NO PRAZO')], max_length=100, null=True)),
                ('obs_contrato', models.TextField(blank=True, max_length=400, null=True)),
                ('necessidade_contratacao', models.DateField(blank=True, null=True)),
                ('status_contratacao', models.CharField(blank=True, choices=[('I', 'DENTRO DO PRAZO'), ('II', 'CONTRATADO'), ('III', 'VENCIDO')], max_length=100, null=True)),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.centrodecusto')),
                ('fiscal_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='contract.colaborador')),
                ('fiscal_substituto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_substituto', to='contract.colaborador')),
            ],
            options={
                'verbose_name': 'Linha Orçamentaria',
                'verbose_name_plural': 'Linhas Orçamentarias',
            },
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aditivo', models.DateField()),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('novo_prazo', models.DateField(blank=True, null=True)),
                ('novo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='contract.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('centro', models.CharField(choices=[('I', 'DOP'), ('II', 'GELOG'), ('III', 'GEOPE'), ('IV', 'GESAS')], max_length=10)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'unique_together': {('ano', 'centro')},
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='ano_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.orcamento'),
        ),
        migrations.CreateModel(
            name='OrcamentoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deduction', models.BooleanField(default=False, verbose_name='Retirada de orçamento')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('diretoria', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_custo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.orcamento')),
            ],
        ),
    ]
