# Generated by Django 5.0.6 on 2024-06-11 17:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orcamentoexterno',
            options={'verbose_name': 'Orçamento Externo', 'verbose_name_plural': 'Orçamentos Externos'},
        ),
        migrations.RenameField(
            model_name='aditivo',
            old_name='novo_prazo',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='aditivo',
            old_name='novo_valor',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='data_prevista_tr',
            new_name='data_assinatura',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='necessidade_contratacao',
            new_name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='aditivo',
            name='data_aditivo',
        ),
        migrations.RemoveField(
            model_name='aditivo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='centrodecusto',
            name='centro_gestor',
        ),
        migrations.RemoveField(
            model_name='centrodecusto',
            name='centro_solicitante',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='ano_orcamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='classificacao_orcamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='custo_despesa',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='descricao_resumida',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fiscal_principal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fiscal_substituto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='mes_referencia',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='obs_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='remanejamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_contratacao',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_elaboracao_tr',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_processo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_orcado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_utilizado',
        ),
        migrations.RemoveField(
            model_name='orcamentoexterno',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='orcamentoexterno',
            name='diretoria',
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='diretoria',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='gerencia',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='gerencia',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='orcamentoexterno',
            name='centro',
            field=models.CharField(choices=[('I', 'DOP'), ('II', 'GELOG'), ('III', 'GEOPE'), ('IV', 'GESAS')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contract.contrato'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='centro',
            field=models.CharField(choices=[('I', 'DOP'), ('II', 'GELOG'), ('III', 'GEOPE'), ('IV', 'GESAS')], default=django.utils.timezone.now, max_length=10),
        ),
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_externos', to='contract.orcamento'),
        ),
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='is_deduction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LinhaOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, choices=[('I', 'OPEX'), ('II', 'CAPEX')], max_length=100, null=True)),
                ('custo_despesa', models.CharField(choices=[('I', 'Base Principal'), ('II', 'Serviços Especializados'), ('III', 'Despesas Compartilhadas'), ('IV', 'Máquinas e Equipamentos'), ('V', 'Equip. de Informática'), ('VI', 'Software e Licenças')], default='I', max_length=100)),
                ('descricao_resumida', models.CharField(blank=True, max_length=255, null=True)),
                ('classificacao_orcamento', models.CharField(blank=True, choices=[('NOVO', 'NOVO'), ('RENOVAÇÃO', 'RENOVAÇÃO'), ('CARY OVER', 'CARY OVER'), ('REPLANEJAMENTO', 'REPLANEJAMENTO')], max_length=100, null=True)),
                ('status_processo', models.CharField(blank=True, choices=[('I', 'PLANEJAMENTO'), ('II', 'Execução'), ('III', 'Elaboração de TR'), ('IV', 'Cotação'), ('V', 'Em proc. aditivo')], max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('I', 'SERVIÇO'), ('II', 'FORNECIMENTO'), ('III', 'ASSINATURA'), ('IV', 'FORNECIMENTO/SERVIÇO')], max_length=100, null=True)),
                ('valor_orcado', models.FloatField(blank=True, default=0, null=True)),
                ('valor_utilizado', models.FloatField(blank=True, default=0, null=True)),
                ('remanejamento', models.FloatField(blank=True, default=0, null=True)),
                ('mes_referencia', models.CharField(blank=True, max_length=7, null=True)),
                ('data_prevista_tr', models.DateField(blank=True, null=True)),
                ('status_elaboracao_tr', models.CharField(blank=True, choices=[('I', 'VENCIDO'), ('II', 'DENTRO DO PRAZO'), ('III', 'ELABORADO COM ATRASO'), ('IV', 'ELABORADO NO PRAZO')], max_length=100, null=True)),
                ('obs_contrato', models.TextField(blank=True, max_length=400, null=True)),
                ('necessidade_contratacao', models.DateField(blank=True, null=True)),
                ('status_contratacao', models.CharField(blank=True, choices=[('I', 'DENTRO DO PRAZO'), ('II', 'CONTRATADO'), ('III', 'VENCIDO')], max_length=100, null=True)),
                ('ano_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.orcamento')),
                ('centro_custo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.centrodecusto')),
                ('possivel_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='contract.colaborador')),
            ],
            options={
                'verbose_name': 'Linha Orçamentária',
                'verbose_name_plural': 'Linhas Orçamentárias',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='contract.linhaorcamentaria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Remanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_remanejamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('linha_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_destino', to='contract.linhaorcamentaria')),
                ('linha_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_origem', to='contract.linhaorcamentaria')),
            ],
            options={
                'verbose_name': 'Remanejamento',
                'verbose_name_plural': 'Remanejamentos',
            },
        ),
    ]
