# Generated by Django 5.0.7 on 2024-08-15 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fical_principal',
            new_name='fiscal_principal',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fical_substituto',
            new_name='fiscal_substituto',
        ),
        migrations.AddField(
            model_name='contrato',
            name='num_prestacoes',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.linhaorcamentaria'),
        ),
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status_pagamento', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.contrato')),
            ],
        ),
    ]
