# Generated by Django 5.0.6 on 2024-06-14 19:26

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCustoGestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='centro_custo',
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orcamentoexterno',
            options={'verbose_name': 'Orçamento Externo', 'verbose_name_plural': 'Orçamentos Externos'},
        ),
        migrations.RenameField(
            model_name='aditivo',
            old_name='novo_prazo',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='aditivo',
            old_name='novo_valor',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='data_prevista_tr',
            new_name='data_assinatura',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='necessidade_contratacao',
            new_name='data_vencimento',
        ),
        migrations.RemoveField(
            model_name='aditivo',
            name='data_aditivo',
        ),
        migrations.RemoveField(
            model_name='aditivo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='fone',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='ano_orcamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='classificacao_orcamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='custo_despesa',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='descricao_resumida',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fiscal_principal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fiscal_substituto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='mes_referencia',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='obs_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='remanejamento',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_contratacao',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_elaboracao_tr',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='status_processo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_orcado',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_utilizado',
        ),
        migrations.RemoveField(
            model_name='orcamentoexterno',
            name='centro_custo',
        ),
        migrations.RemoveField(
            model_name='orcamentoexterno',
            name='diretoria',
        ),
        migrations.AddField(
            model_name='aditivo',
            name='justificativa',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='ramal',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fical_principal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='contract.colaborador', verbose_name='Fiscal Principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='fical_substituto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_substituto', to='contract.colaborador', verbose_name='Fiscal Substituto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_protocolo',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='classe',
            field=models.CharField(blank=True, choices=[('A', 'OPEX'), ('B', 'CAPEX')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_adicionado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_subtraido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamentoexterno',
            name='centro',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orcamentoexterno',
            name='classe',
            field=models.CharField(blank=True, choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aditivo',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aditivos', to='contract.contrato'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_externos', to='contract.orcamento'),
        ),
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='is_deduction',
            field=models.BooleanField(default=False, verbose_name='Envio de Orçamento'),
        ),
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.centrodecustogestor'),
        ),
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('ano', 'centro', 'classe')},
        ),
        migrations.CreateModel(
            name='CentroDeCustoSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('centro_gestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='contract.centrodecustogestor')),
            ],
            options={
                'unique_together': {('centro_gestor', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='LinhaOrcamentaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(blank=True, choices=[('A', 'OPEX'), ('B', 'CAPEX')], max_length=100, null=True)),
                ('custo_despesa', models.CharField(choices=[('A', 'Base Principal'), ('B', 'Serviços Especializados'), ('C', 'Despesas Compartilhadas'), ('D', 'Máquinas e Equipamentos'), ('E', 'Equip. de Informática'), ('F', 'Software e Licenças'), ('G', 'Input da Base Principal'), ('H', 'Contribuições em Geral'), ('I', 'Locação de Bens e Móveis'), ('J', 'Fardamento e EPI'), ('L', 'Assinaturas e Publicações')], max_length=100, verbose_name='CUSTO/DESPESA')),
                ('descricao_resumida', models.CharField(blank=True, max_length=255, null=True, verbose_name='Finalidade')),
                ('classificacao_orcamento', models.CharField(blank=True, choices=[('NOVO', 'NOVO'), ('RENOVAÇÃO', 'RENOVAÇÃO'), ('CARY OVER', 'CARY OVER'), ('REPLANEJAMENTO', 'REPLANEJAMENTO'), ('N/A', 'N/A')], max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('I', 'SERVIÇO'), ('II', 'FORNECIMENTO'), ('III', 'ASSINATURA'), ('IV', 'FORNECIMENTO/SERVIÇO')], max_length=100, null=True)),
                ('tipo_provavel_contratacao', models.CharField(choices=[('A', 'LICITAÇÃO'), ('B', 'DISPENSA EM RAZÃO DO VALOR'), ('C', 'CONVÊNIO'), ('D', 'FUNDO FIXO'), ('E', 'INEXIGIBILIDADE'), ('F', 'ATA DE REGISTRO DE PREÇO'), ('H', 'ACORDO DE COOPERAÇÃO'), ('I', 'APOSTILAMENTO')], max_length=100)),
                ('valor_orcado', models.FloatField(blank=True, default=0, null=True)),
                ('status_elaboracao_tr', models.CharField(blank=True, choices=[('I', 'VENCIDO'), ('II', 'DENTRO DO PRAZO'), ('III', 'ELABORADO COM ATRASO'), ('IV', 'ELABORADO NO PRAZO')], max_length=100, null=True)),
                ('necessidade_contratacao', models.DateField(blank=True, null=True)),
                ('status_processo', models.CharField(blank=True, choices=[('I', 'PLANEJAMENTO'), ('II', 'Execução'), ('III', 'Elaboração de TR'), ('IV', 'Cotação'), ('V', 'Em proc. aditivo')], max_length=100, null=True)),
                ('status_contratacao', models.CharField(blank=True, choices=[('A', 'DENTRO DO PRAZO'), ('B', 'CONTRATADO NO PRAZO'), ('C', 'CONTRATADO COM ATRASO'), ('D', 'PRAZO VENCIDO'), ('E', 'LINHA TOTALMENTE REMANEJADA'), ('F', 'LINHA TOTALMENTE EXECUTADA'), ('G', 'LINHA DE PAGAMENTO'), ('H', 'LINHA PARCIALMENTE REMANEJADA'), ('I', 'LINHA PARCIALMENTE EXECUTADA'), ('J', 'N/A')], max_length=100, null=True)),
                ('obs_contrato', models.TextField(blank=True, max_length=400, null=True)),
                ('ano_orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.orcamento')),
                ('centro_custo_gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.centrodecustogestor')),
                ('centro_custo_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.centrodecustosolicitante')),
                ('possivel_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_possivel', to='contract.colaborador', verbose_name='Fiscal')),
            ],
            options={
                'verbose_name': 'Linha Orçamentária',
                'verbose_name_plural': 'Linhas Orçamentárias',
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='contract.linhaorcamentaria'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Remanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_remanejamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('linha_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_destino', to='contract.linhaorcamentaria')),
                ('linha_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remanejamentos_origem', to='contract.linhaorcamentaria')),
            ],
            options={
                'verbose_name': 'Remanejamento',
                'verbose_name_plural': 'Remanejamentos',
            },
        ),
        migrations.CreateModel(
            name='Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diretoria', models.CharField(max_length=10)),
                ('gerencia', models.CharField(max_length=10)),
                ('setor', models.CharField(max_length=100, unique=True, verbose_name='Setor')),
            ],
            options={
                'unique_together': {('diretoria', 'gerencia', 'setor')},
            },
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contract.setores', to_field='setor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CentroDeCusto',
        ),
    ]
