# Generated by Django 5.0.6 on 2024-06-12 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linhaorcamentaria',
            name='remanejamento',
        ),
        migrations.AddField(
            model_name='centrodecusto',
            name='setor',
            field=models.CharField(default=0, max_length=100, verbose_name='Setor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linhaorcamentaria',
            name='tipo_provavel_contratacao',
            field=models.CharField(choices=[('A', 'LICITAÇÃO'), ('B', 'DISPENSA EM RAZÃO DO VALOR'), ('C', 'CONVÊNIO'), ('D', 'FUNDO FIXO'), ('E', 'INEXIGIBILIDADE'), ('F', 'ATA DE REGISTRO DE PREÇO'), ('H', 'ACORDO DE COOPERAÇÃO'), ('I', 'APOSTILAMENTO')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.centrodecusto', verbose_name='Centro de custo solicitante'),
        ),
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='classificacao_orcamento',
            field=models.CharField(blank=True, choices=[('NOVO', 'NOVO'), ('RENOVAÇÃO', 'RENOVAÇÃO'), ('CARY OVER', 'CARY OVER'), ('REPLANEJAMENTO', 'REPLANEJAMENTO'), ('N/A', 'N/A')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='custo_despesa',
            field=models.CharField(choices=[('A', 'Base Principal'), ('B', 'Serviços Especializados'), ('C', 'Despesas Compartilhadas'), ('D', 'Máquinas e Equipamentos'), ('E', 'Equip. de Informática'), ('F', 'Software e Licenças'), ('G', 'Input da Base Principal'), ('H', 'Contribuições em Geral'), ('I', 'Locação de Bens e Móveis'), ('J', 'Fardamento e EPI'), ('L', 'Assinaturas e Publicações')], max_length=100, verbose_name='CUSTO/DESPESA'),
        ),
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='descricao_resumida',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Finalidade'),
        ),
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='possivel_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='contract.colaborador', verbose_name='Fiscal'),
        ),
    ]
