# Generated by Django 5.0.6 on 2024-06-18 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_centrodecustogestor_remove_contrato_centro_custo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Direcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='setor',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='coordenacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='contract.coordenacao'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='direcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='contract.direcao'),
        ),
        migrations.CreateModel(
            name='Gerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('direcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerencias', to='contract.direcao')),
            ],
        ),
        migrations.AddField(
            model_name='coordenacao',
            name='gerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacoes', to='contract.gerencia'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='contract.gerencia'),
        ),
        migrations.DeleteModel(
            name='Setores',
        ),
    ]
