# Generated by Django 5.0.6 on 2024-05-22 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_fiscal_mat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Linha Orçamentaria', 'verbose_name_plural': 'Linhas Orçamentarias'},
        ),
        migrations.AlterModelOptions(
            name='fiscal',
            options={'verbose_name': 'Fiscal', 'verbose_name_plural': 'Fiscais'},
        ),
        migrations.AlterModelOptions(
            name='orcamento',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ano_orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.orcamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='centro_custo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.centrodecusto'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='contract.fiscal'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_substituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_substituto', to='contract.fiscal'),
        ),
        migrations.AlterField(
            model_name='fiscal',
            name='mat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matrícula'),
        ),
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aditivo', models.DateField()),
                ('descricao', models.TextField(blank=True, max_length=500, null=True)),
                ('novo_prazo', models.DateField(blank=True, null=True)),
                ('novo_valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aditivos', to='contract.contrato')),
            ],
        ),
    ]
