# Generated by Django 5.0.7 on 2024-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_rename_fical_principal_contrato_fiscal_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='num_prestacoes',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
