# Generated by Django 5.0.6 on 2024-06-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_coordenacao_direcao_remove_colaborador_setor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenacao',
            options={'verbose_name': 'Coordenação', 'verbose_name_plural': 'Coordenações'},
        ),
        migrations.AlterModelOptions(
            name='direcao',
            options={'verbose_name': 'Direção', 'verbose_name_plural': 'Direções'},
        ),
        migrations.AlterModelOptions(
            name='gerencia',
            options={'verbose_name': 'Gerência', 'verbose_name_plural': 'Gerências'},
        ),
        migrations.AlterUniqueTogether(
            name='coordenacao',
            unique_together={('gerencia', 'nome')},
        ),
        migrations.AlterUniqueTogether(
            name='gerencia',
            unique_together={('direcao', 'nome')},
        ),
    ]
