# Generated by Django 5.0.6 on 2024-05-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contrato_options_alter_fiscal_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fiscal',
            new_name='Colaborador',
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name': 'Colaborador', 'verbose_name_plural': 'Colaboradores'},
        ),
    ]
