# Generated by Django 5.0.6 on 2024-06-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_coordenacao_options_alter_direcao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='linha_orcamentaria',
        ),
        migrations.AddField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ManyToManyField(related_name='contrato', to='contract.linhaorcamentaria'),
        ),
    ]
