# Generated by Django 5.0.6 on 2024-06-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_rename_fiscal_colaborador_alter_colaborador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrcamentoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(blank=True, null=True)),
                ('diretoria', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_custo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.orcamento')),
            ],
        ),
    ]
