# Generated by Django 5.0.6 on 2024-06-27 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_remove_contrato_linha_orcamentaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='linha_orcamentaria',
        ),
        migrations.AddField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='contract.linhaorcamentaria'),
            preserve_default=False,
        ),
    ]
