# Generated by Django 5.0.7 on 2024-08-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_centrodecustogestor_nome_alter_colaborador_mat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='objeto',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Objeto'),
        ),
    ]
