# Generated by Django 5.0.6 on 2024-06-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_rename_celular_colaborador_ramal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='numero_contrato',
        ),
        migrations.AddField(
            model_name='aditivo',
            name='justificativa',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colaborador',
            name='setor',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='fical_principal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='contract.colaborador', verbose_name='Fiscal Principal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='fical_substituto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_substituto', to='contract.colaborador', verbose_name='Fiscal Substituto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_protocolo',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='possivel_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_possivel', to='contract.colaborador', verbose_name='Fiscal'),
        ),
    ]
