# Generated by Django 5.0.6 on 2024-06-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_orcamentoexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='centro',
            field=models.CharField(choices=[('I', 'DOP'), ('II', 'GELOG'), ('III', 'GEOPE'), ('IV', 'GESAS')], default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OrcamentoExterno',
        ),
    ]
