# Generated by Django 5.0.6 on 2024-06-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_orcamentoexterno'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentoexterno',
            name='is_deduction',
            field=models.BooleanField(default=False),
        ),
    ]
