# Generated by Django 5.0.6 on 2024-06-05 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0004_alter_qualificacaocooporativa_baneficiado'),
        ('collaborator', '0001_initial'),
        ('contract', '0006_orcamentoexterno_is_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_principal', to='collaborator.colaborador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_substituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_substituto', to='collaborator.colaborador'),
        ),
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='is_deduction',
            field=models.BooleanField(default=False, verbose_name='Retirada de orçamento'),
        ),
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
