# Generated by Django 5.0.7 on 2024-08-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_alter_linhaorcamentaria_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='classe',
            field=models.CharField(blank=True, choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=100, null=True, verbose_name='Tipo de linha'),
        ),
    ]
