# Generated by Django 5.0.6 on 2024-06-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_orcamento_centro_delete_orcamentoexterno'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orcamento',
            unique_together={('ano', 'centro')},
        ),
    ]
