# Generated by Django 5.0.6 on 2024-06-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_remove_contrato_linha_orcamentaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhaorcamentaria',
            name='objeto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Objeto'),
        ),
    ]
