# Generated by Django 5.0.6 on 2024-07-16 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_linhaorcamentaria_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linhaorcamentaria',
            name='classe',
            field=models.CharField(blank=True, choices=[('A', 'OPEX'), ('B', 'CAPEX')], max_length=100, null=True, verbose_name='Tipo de linha'),
        ),
        migrations.CreateModel(
            name='Auxilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('demandantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxilios', to='contract.centrodecustogestor', verbose_name='Demandantes')),
            ],
            options={
                'verbose_name': 'Auxílio',
                'verbose_name_plural': 'Auxílios',
            },
        ),
    ]
