# Generated by Django 5.0.6 on 2024-06-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_alter_orcamento_unique_together_orcamento_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamentoexterno',
            name='classe',
            field=models.CharField(blank=True, choices=[('OPEX', 'OPEX'), ('CAPEX', 'CAPEX')], max_length=100, null=True),
        ),
    ]
