# Generated by Django 5.0.6 on 2024-06-05 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_orcamento_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='centro',
            field=models.CharField(choices=[('I', 'DOP'), ('II', 'GELOG'), ('III', 'GEOPE'), ('IV', 'GESAS')], max_length=10),
        ),
    ]
