# Generated by Django 5.0.6 on 2024-06-13 17:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_alter_orcamentoexterno_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='valor_adicionado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='valor_subtraido',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
