# Generated by Django 5.0.7 on 2024-07-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_remove_orcamento_valor_adicionado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentoexterno',
            name='is_deduction',
        ),
        migrations.AddField(
            model_name='orcamentoexterno',
            name='tipo_movimentacao',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('retirada', 'Retirada')], default=0, max_length=8),
            preserve_default=False,
        ),
    ]
