# Generated by Django 5.0.6 on 2024-06-13 18:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_orcamento_valor_adicionado_orcamento_valor_subtraido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros', to='contract.centrodecusto'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
