# Generated by Django 5.0.7 on 2024-09-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_remove_prestacao_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestacao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
