# Generated by Django 5.0.6 on 2024-06-13 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_alter_orcamento_centro_alter_orcamento_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.centrodecusto'),
        ),
    ]
