# Generated by Django 5.0.7 on 2024-07-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_remove_orcamentoexterno_is_deduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhaorcamentaria',
            name='status_linha_orcamentaria',
            field=models.CharField(blank=True, choices=[('I', 'SERVIÇO'), ('II', 'FORNECIMENTO'), ('III', 'ASSINATURA'), ('IV', 'FORNECIMENTO/SERVIÇO')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='linhaorcamentaria',
            name='valor_aprovisionado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
