# Generated by Django 5.0.6 on 2024-06-13 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_alter_orcamento_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='gerencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.centrodecusto'),
        ),
    ]
