# Generated by Django 5.0.7 on 2024-09-06 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_remove_contrato_num_prestacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='tipo_pagamento',
        ),
        migrations.AddField(
            model_name='contrato',
            name='num_prestacoes',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
