# Generated by Django 5.0.7 on 2024-07-29 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_alter_linhaorcamentaria_valor_aprovisionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='coordenacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.coordenacao'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='direcao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.direcao'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='gerencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.gerencia'),
        ),
    ]
