# Generated by Django 5.0.7 on 2024-07-29 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_alter_colaborador_direcao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Auxilio',
        ),
    ]
