# Generated by Django 5.0.7 on 2024-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_prestacao_numero_parcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='num_prestacoes',
        ),
        migrations.AddField(
            model_name='contrato',
            name='natureza_pagamento',
            field=models.CharField(choices=[('PAGAMENTO ÚNICO', 'PAGAMENTO ÚNICO'), ('PAGAMENTO ANUAL', 'PAGAMENTO ANUAL'), ('PAGAMENTO SEMANAL', 'PAGAMENTO SEMANAL'), ('PAGAMENTO MENSAL', 'PAGAMENTO MENSAL'), ('PAGAMENTO QUIZENAL', 'PAGAMENTO QUINZENAL'), ('PAGAMENTO TRIMESTRAL', 'PAGAMENTO TRIMESTRAL'), ('PAGAMENTO SEMESTRAL', 'PAGAMENTO SEMESTRAL'), ('PAGAMENTO SOB DEMANDA', 'PAGAMENTO SOB DEMANDA')], default=0, max_length=30),
            preserve_default=False,
        ),
    ]
