# Generated by Django 5.0.7 on 2024-07-31 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_contrato_valor_contrato_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linhaorcamentaria',
            old_name='valor_aprovisionado',
            new_name='_valor_aprovisionado',
        ),
    ]
