# Generated by Django 5.0.7 on 2024-08-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_rename_valor_aprovisionado_linhaorcamentaria__valor_aprovisionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_protocolo',
            field=models.CharField(blank=True, editable=False, max_length=7, unique=True),
        ),
    ]
