# Generated by Django 5.0.7 on 2024-08-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_alter_contrato_numero_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aditivo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_protocolo',
            field=models.CharField(blank=True, editable=False, max_length=7, unique=True, verbose_name='Contrato'),
        ),
    ]
