# Generated by Django 5.0.7 on 2024-08-08 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_alter_aditivo_valor_alter_contrato_numero_protocolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='mes_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='quantidade_prestacoes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Prestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_prestacao', models.PositiveIntegerField()),
                ('valor_prestacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_prestacao', models.DateField()),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='contract.contrato')),
            ],
        ),
    ]
