# Generated by Django 5.0.7 on 2024-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_remove_contrato_fical_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_vencimento',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='data_pagamento',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
