# Generated by Django 5.0.7 on 2024-08-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0022_alter_contrato_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestacao',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
