# Generated by Django 5.0.7 on 2024-08-11 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_alter_prestacao_data_pagamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestacao',
            options={'ordering': ['numero']},
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='num_prestacoes',
        ),
        migrations.AlterUniqueTogether(
            name='prestacao',
            unique_together={('contrato', 'numero')},
        ),
        migrations.AddField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('em_espera', 'Em Espera'), ('em_execucao', 'Em Execução'), ('finalizado', 'Finalizado')], default='em_espera', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='contract.linhaorcamentaria'),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestações', to='contract.contrato'),
        ),
        migrations.RemoveField(
            model_name='prestacao',
            name='data_pagamento',
        ),
    ]
