# Generated by Django 5.0.7 on 2024-08-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_alter_prestacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestacao',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='prestacao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contrato',
            name='num_prestacoes',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestacoes', to='contract.contrato'),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='data_vencimento',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='prestacao',
            name='numero',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
