# Generated by Django 5.0.7 on 2024-08-11 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0025_alter_prestacao_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='data_vencimento',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='fiscal_principal',
            new_name='fical_principal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='fiscal_substituto',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='num_prestacoes',
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fical_substituto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='contratos_fiscal_substituto', to='contract.colaborador', verbose_name='Fiscal Substituto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.linhaorcamentaria'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='status',
            field=models.CharField(choices=[('em_espera', 'Em Espera'), ('em_execucao', 'Em Execução'), ('finalizado', 'Finalizado')], default='em_espera', max_length=20),
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(editable=False)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('paga', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='contract.contrato')),
            ],
        ),
        migrations.DeleteModel(
            name='Prestacao',
        ),
    ]
