# Generated by Django 5.0.7 on 2024-08-11 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0026_rename_data_vencimento_contrato_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato', to='contract.linhaorcamentaria'),
        ),
    ]
