# Generated by Django 5.0.7 on 2024-08-11 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_alter_contrato_linha_orcamentaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='linha_orcamentaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos', to='contract.linhaorcamentaria'),
        ),
    ]
