# Generated by Django 5.0.6 on 2024-06-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(max_length=15, verbose_name='Ramal'),
        ),
    ]
