# Generated by Django 5.0.6 on 2024-06-19 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_nome_alter_customuser_telefone'),
        ('contract', '0004_alter_coordenacao_options_alter_direcao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coordenacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.coordenacao'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='direcao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.direcao'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gerencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.gerencia'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='perfil',
            field=models.CharField(choices=[('presidencia', 'Presidência'), ('diretor', 'Diretor'), ('gerente', 'Gerente'), ('coordenador', 'Coordenador'), ('analista', 'Analista')], default=0, max_length=20),
            preserve_default=False,
        ),
    ]
