# Generated by Django 5.0.7 on 2024-08-02 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_alter_aditivo_valor_alter_contrato_numero_protocolo'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='matricula',
        ),
        migrations.AddField(
            model_name='usuario',
            name='mat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='coordenacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.coordenacao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direcao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.direcao'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='gerencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.gerencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome_completo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
