# Generated by Django 5.0.7 on 2024-07-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0010_remove_orcamentoexterno_is_deduction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auxilio_Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('A', 'Graduação'), ('B', 'Pós-Graduação'), ('C', 'Auxilio creche escola')], max_length=100, null=True)),
                ('valor_parcela', models.FloatField(blank=True, null=True)),
                ('valor_total', models.FloatField(blank=True, editable=False, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('mes_inicio', models.DateField()),
                ('qtd_parcelas', models.PositiveIntegerField()),
                ('mes_fim', models.DateField(editable=False)),
                ('baneficiado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.colaborador')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualificacoes', to='contract.orcamento')),
            ],
        ),
    ]
