# Generated by Django 5.0.7 on 2024-07-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxilio_colaborador',
            options={'verbose_name': 'Qualificação Coorporativa', 'verbose_name_plural': 'Qualificações Coorporativas'},
        ),
    ]
