# Generated by Django 5.0.7 on 2024-09-04 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliocolaborador',
            name='valor_total',
            field=models.FloatField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
