# Generated by Django 5.0.7 on 2024-07-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0002_alter_auxilio_colaborador_options'),
        ('contract', '0010_remove_orcamentoexterno_is_deduction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auxilio_Colaborador',
            new_name='AuxilioColaborador',
        ),
        migrations.AlterModelOptions(
            name='auxiliocolaborador',
            options={'verbose_name': 'Auxilio', 'verbose_name_plural': 'Auxilios'},
        ),
    ]
