# Generated by Django 5.0.7 on 2024-09-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0003_alter_auxiliocolaborador_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auxiliocolaborador',
            old_name='baneficiado',
            new_name='beneficiado',
        ),
        migrations.AlterField(
            model_name='auxiliocolaborador',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Graduação', 'Graduação'), ('Pós-Graduação', 'Pós-Graduação'), ('Auxílio creche escola', 'Auxílio creche escola'), ('Língua estrangeira', 'Língua estrangeira')], max_length=100, null=True),
        ),
    ]
