# Generated by Django 5.0.7 on 2024-07-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0003_rename_auxilio_colaborador_auxiliocolaborador_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliocolaborador',
            options={'verbose_name': 'Auxílio Colaborador', 'verbose_name_plural': 'Auxílios Colaboradores'},
        ),
    ]
