# Generated by Django 5.0.7 on 2024-07-25 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0004_alter_auxiliocolaborador_options'),
        ('contract', '0010_remove_orcamentoexterno_is_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliocolaborador',
            name='orcamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auxilios_colaboradores', to='contract.orcamento'),
        ),
    ]
