# Generated by Django 5.0.7 on 2024-07-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0008_alter_auxiliocolaborador_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliocolaborador',
            options={},
        ),
    ]
