# Generated by Django 5.0.7 on 2024-07-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0009_alter_auxiliocolaborador_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auxiliocolaborador',
            name='ativo',
        ),
        migrations.AddField(
            model_name='auxiliocolaborador',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando'), ('ativo', 'Ativo'), ('finalizado', 'Finalizado')], default='aguardando', max_length=10),
        ),
    ]
