# Generated by Django 5.0.7 on 2024-07-29 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auxilios', '0010_remove_auxiliocolaborador_ativo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auxiliocolaborador',
            options={'verbose_name': 'Auxílio Colaborador', 'verbose_name_plural': 'Auxílios Colaboradores'},
        ),
    ]
