# Generated by Django 5.0.6 on 2024-05-23 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0004_rename_fiscal_colaborador_alter_colaborador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificacaoCooporativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('A', 'Graduação'), ('B', 'Formação técnica'), ('C', 'Especialização'), ('D', 'Mestrado'), ('E', 'MBA'), ('F', 'Doutorado'), ('G', 'Auxilio creche escola')], max_length=100, null=True)),
                ('demandante', models.CharField(blank=True, choices=[('A', 'GESAS'), ('B', 'GEOPE'), ('C', 'GELOG')], max_length=100, null=True)),
                ('valor_orcado', models.FloatField(blank=True, null=True)),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('baneficiado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.colaborador')),
            ],
        ),
    ]
