# Generated by Django 5.0.7 on 2024-07-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0001_initial'),
        ('contract', '0010_remove_orcamentoexterno_is_deduction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificacaocooporativa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'Graduação'), ('B', 'Pós-Graduação'), ('C', 'Auxilio creche escola')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='qualificacaocooporativa',
            name='demandante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='contract.centrodecustogestor'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnoAuxilio',
        ),
    ]
