# Generated by Django 5.0.6 on 2024-05-24 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_anoauxilio_alter_qualificacaocooporativa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='anoauxilio',
            name='valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='anoauxilio',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='qualificacaocooporativa',
            name='tipo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aid.anoauxilio'),
            preserve_default=False,
        ),
    ]
