# Generated by Django 5.0.6 on 2024-06-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_anoauxilio_valor_alter_anoauxilio_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificacaocooporativa',
            name='tipo',
            field=models.CharField(blank=True, choices=[('A', 'Graduação'), ('B', 'Formação técnica'), ('C', 'Especialização'), ('D', 'Mestrado'), ('E', 'MBA'), ('F', 'Doutorado'), ('G', 'Auxilio creche escola')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AnoAuxilio',
        ),
    ]
