# Generated by Django 5.0.6 on 2024-06-05 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_anoauxilio_valor_alter_anoauxilio_ano_and_more'),
        ('collaborator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualificacaocooporativa',
            name='baneficiado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='collaborator.colaborador'),
        ),
    ]
